SCRIPTFORGE#ifndef SCRIPTFORGE_DEFINE_HPP
#define SCRIPTFORGE_DEFINE_HPP


#define SCRIPTFORGE_BEGIN namespace Scriptforge {
#define SCRIPTFORGE_END }
#define SCRIPTFORGE /*::*/Scriptforge::


#define SCRIPTFORGE_ARGV_BEGIN SCRIPTFORGE_BEGIN inline namespace Argv {
#define SCRIPTFORGE_ARGV_END   SCRIPTFORGE_END }

#define SCRIPTFORGE_ARGV SCRIPTFORGE Argv::
#define SCRIPTFORGE_ARGVCLI SCRIPTFORGE_ARGV BasicArgvCli<HashT>::
#define SCRIPTFORGE_ARGVCLI_TEM template<isHash HashT>


#define SCRIPTFORGE_BASE_BEGIN SCRIPTFORGE_BEGIN inline namespace Base {
#define SCRIPTFORGE_BASE_END   SCRIPTFORGE_END }

#define SCRIPTFORGE_BASE SCRIPTFORGE Base::
#define SCRIPTFORGE_BASE64 SCRIPTFORGE_BASE BasicBase64<CharSet>::
#define  SCRIPTFORGE_BASE64_TEM template<isBaseCharSet CharSet>


#define SCRIPTFORGE_BUFFER_BEGIN SCRIPTFORGE_BEGIN inline namespace Buffer {
#define  SCRIPTFORGE_BUFFER_END   SCRIPTFORGE_END }

#define SCRIPTFORGE_BUFFER_LITERALS_BEGIN inline namespace BufferLiterals {
#define SCRIPTFORGE_BUFFER_LITERALS_END }

#define SCRIPTFORGE_BUFFER SCRIPTFORGE Buffer::
#define SCRIPTFORGE_BYTEBUFFER_A SCRIPTFORGE_BUFFER BasicByteBuffer<Alloc>
#define SCRIPTFORGE_BYTEBUFFER SCRIPTFORGE_BUFFER BasicByteBuffer<Alloc>::
#define SCRIPTFORGE_BYTEBUFFER_TEM_BEGIN template <typename Alloc
#define SCRIPTFORGE_BYTEBUFFER_TEM_END >
#define SCRIPTFORGE_BYTEBUFFER_TEM SCRIPTFORGE_BYTEBUFFER_TEM_BEGIN SCRIPTFORGE_BYTEBUFFER_TEM_END


#define SCRIPTFORGE_CODE_BEGIN SCRIPTFORGE_BEGIN namespace Code {
#define SCRIPTFORGE_CODE_END SCRIPTFORGE_END } 
#define SCRIPTFORGE_CODE SCRIPTFORGE Code::


#define SCRIPTFORGE_CONCEPT_BEGIN SCRIPTFORGE_BEGIN namespace Concept {
#define SCRIPTFORGE_CONCEPT_END SCRIPTFORGE_END } 
#define SCRIPTFORGE_CONCEPT SCRIPTFORGE Concept::


#define SCRIPTFORGE_ERR_BEGIN SCRIPTFORGE_BEGIN inline namespace Err {
#define SCRIPTFORGE_ERR_END   SCRIPTFORGE_END }

#define SCRIPTFORGE_ERR SCRIPTFORGE Err::
#define SCRIPTFORGE_ERROR_A SCRIPTFORGE_ERR BasicError<CodeT, T, Clock>
#define SCRIPTFORGE_ERROR SCRIPTFORGE_ERR BasicError<CodeT, T, Clock>::
#define SCRIPTFORGE_ERROR_TEM_A template <typename CodeT, typename T, typename Clock>
#define SCRIPTFORGE_ERROR_TEM SCRIPTFORGE_ERROR_TEM_A \
                          requires ErrorRequires<CodeT, T, Clock>


#define SCRIPTFORGE_MSG_BEGIN SCRIPTFORGE_BEGIN inline namespace Msg {
#define SCRIPTFORGE_MSG_END   SCRIPTFORGE_END }

#define SCRIPTFORGE_MSG SCRIPTFORGE Msg::
#define SCRIPTFORGE_MESSAGE_A SCRIPTFORGE_MSG BasicMessage<T, Clock>
#define SCRIPTFORGE_MESSAGE SCRIPTFORGE_MSG BasicMessage<T, Clock>::
#define SCRIPTFORGE_MESSAGE_TEM_A template <typename T, typename Clock>
#define SCRIPTFORGE_MESSAGE_TEM SCRIPTFORGE_MESSAGE_TEM_A \
                          requires MessageRequires<T, Clock>


#define SCRIPTFORGE_STRINGCONVERSION_BEGIN SCRIPTFORGE_BEGIN inline namespace StringConversion {
#define SCRIPTFORGE_STRINGCONVERSION_END SCRIPTFORGE_END }
#define SCRIPTFORGE_STRINGCONVERSION SCRIPTFORGE StringConversion::


#define SCRIPTFORGE_THREADERROR ThreadError<Async>::
#define SCRIPTFORGE_THREADERROR_TEM template<bool Async>


#define SCRIPTFORGE_THROW_BEGIN SCRIPTFORGE_BEGIN inline namespace Throw {
#define SCRIPTFORGE_THROW_END SCRIPTFORGE_END }
#define SCRIPTFORGE_THROW SCRIPTFORGE Throw::

#endif